apiVersion: apps/v1
kind: Deployment
metadata:
  name: stern-log
spec:
  selector:
    matchLabels:
      app: stern-log
  template:
    metadata:
      labels:
        app: stern-log
    spec:
      containers:
        - name: stern-log-1
          image: busybox
          command:
            - sh
            - -c
            - while true; do echo $(hostname):a; sleep 10; done
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
        - name: stern-log-2
          image: busybox
          command:
            - sh
            - -c
            - while true; do echo $(hostname):b; sleep 10; done
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
