apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo-pod
  template:
    metadata:
      labels:
        app: echo-pod
    spec:
      containers:
        - name: echo
          image: inanimate/echo-server
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
